/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import java.util.stream.Collectors;

public class App {
    public String getGreeting() {
        var list = List.of("hello", "world!");
        return list.map(String::toUpperCase).collect(Collectors.joining(" "));
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
