/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

internal class AppTest {
    @Test
    fun manifoldExtensions() {
        val input = 3
        val output = input * 2

        listOf(input).map { it * 2 } shouldContain output
    }
}

infix fun <T> Iterable<T>.shouldContain(element: T) {
    Assertions.assertTrue(this.contains(element))
}